### ISSUE TITLE
`toString` – an improved `toAsciiBoard`

### ISSUE THREAD

**Issue by alanhussey** [duckpunch/godash#26]
Documenting our offline discussion here:

- Add a new function `toString(board, [overrides])`.
   - Note that this is not `Board.prototype.toString` – leave that as-is.
   - Like `toAsciiBoard`, it takes a `Board` as an argument, but it also takes an optional `overrides` object of `{white, black, empty}`
   - Each property for `overrides` is optional, and should be a single printable character if provided. 
   - The default values for `overrides` are the same values as `toAsciiBoard` (`{white: 'X', black: 'O', empty: '+'}`)
- Rewrite `toAsciiBoard` to be an alias for `toString`, and deprecate it.
- Add examples for `toString`
   - Only overriding some properties: `toString(board, {white: 'W', black: 'B'})`
   - Using non-ASCII characters: `toString(board, {white: '⚪️', black: '⚫️', empty: '➕'})`
      <img width="94" alt="screen shot 2017-05-22 at 1 04 30 pm" src="https://cloud.githubusercontent.com/assets/383725/26326232/3c07dd9a-3eef-11e7-80a6-61fd73ce34ee.png">
   - Getting ridiculous: `toString(board, {white: '🤖', black: '😎', empty: '💩'})`
      <img width="84" alt="screen shot 2017-05-22 at 1 04 34 pm" src="https://cloud.githubusercontent.com/assets/383725/26326231/3c053720-3eef-11e7-8ff2-9061dd7cf46c.png">

**Comment by duckpunch** [comment]
Neat!

Not sure if `toString` is exactly the right name here since there's already a `Board.toString`.

**Comment by duckpunch** [comment]
Actually upon further thought (and after 5 years apparently), `toString` probably makes sense.

This could be implemented by [this request](https://github.com/duckpunch/godash/issues/40#issuecomment-757535371) for better compatibility with [Sabaki](https://github.com/SabakiHQ/Sabaki).
