### ISSUE TITLE
expose number of captures?

### ISSUE THREAD

**Issue by pranaygp** [duckpunch/godash#27]
I think a function that can return the number of captures made by a certain color can be rather useful. The signature could be:

```
godash.captures(board, color) // => Number
```

**Comment by duckpunch** [comment]
Hm.  That doesn't quite work because a board only shows what stones are on the board and doesn't say anything about the game.

**Comment by pranaygp** [comment]
Yeah.. I noticed that after. What I did was store a list of moves (similar to the input for constructBoard), and then calculated the captures by iteratively adding moves and finding difference

**Comment by duckpunch** [comment]
That sounds like a reasonable way to do it!
