### ISSUE TITLE
Add typescript declaration file (TypeScript support)

### ISSUE THREAD

**Issue by abc1236762** [duckpunch/godash#37]
Is there any plan about add TypeScript support? (Add typescript declaration file `.d.ts`)

**Comment by duckpunch** [comment]
I didn't have any plans.

I generally don't use TypeScript, so I didn't have a need for it.  I'd imagine it'd just be adding some configuration and then a Webpack target?

I can take a look at this in the coming week or I'd also be happy to accept a PR :)

**Comment by abc1236762** [comment]
I just forked and working on it, I will send a PR when I finished it.
