### ISSUE TITLE
Version 2 features discussion

### ISSUE THREAD

**Issue by duckpunch** [duckpunch/godash#40]
Feel free to add any ideas you might have.

**Comment by duckpunch** [comment]
I'll break this out into issues later and file them under a milestone.

**Comment by chrisjfoss** [comment]
I would find it helpful to have a `toSignMap` method which would return the signmap of a given board position, to allow the library to have cross-compatibility with the sabaki resources.

It would look pretty similar to the `toAsciiBoard` method that already exists, probably something along the lines of:
```
export function toSignMap(board) {
    const dimensions = board.dimensions;
    let coordinate = 0;
    let sign_map = [];
    for (var i = 0; i < dimensions; i++) {
        for (var j = 0; j < dimensions; j++) {
            let row = [];
            let color = board.moves.get(new Coordinate(i, j), EMPTY);
            switch(color) {
                case BLACK:
                    row.push(1);
                    break;
                case WHITE:
                    row.push(-1);
                    break;
                case EMPTY:
                    row.push(0);
                    break;
            }
        }
        sign_map.push(row);
    }
    return sign_map;
}
```

I haven't tested that code at all, but I think a `toSignMap` method would look something like that.

**Comment by duckpunch** [comment]
Hm - what are the "sabaki resources"?

**Comment by chrisjfoss** [comment]
Sorry, I was referring to the repos in the related section of this github: https://github.com/SabakiHQ/Sabaki#related

The component I was most concerned about compatibility with is the Shudan repo (https://github.com/SabakiHQ/Shudan), which takes a sign map as a parameter when initializing a new board.

**Comment by duckpunch** [comment]
Thanks for the links!

Looks interesting.  I wouldn't say no to a PR :)  (Though there isn't much in the way of development docs - see wishlist)

Otherwise, I'm happy to look into this later (time is tight for me right now).

**Comment by duckpunch** [comment]
@chrisjfoss I think it's unlikely you're waiting on this, but I'll do #26 soon, hopefully, and it'll include your request here.  Thanks for the idea.

**Comment by chrisjfoss** [comment]
@duckpunch Thanks for the heads up!  Although I've abandoned the specific project that kicked off this request, I still am working on some Go-related projects which are heavily dependent on the sabaki resources, so it will be nice having this library as an option for those projects.

**Comment by duckpunch** [comment]
Ok, v2 is released.  `toSignMap` is possible via `Board.toMap({[BLACK]: 1, [WHITE]: -1})`.
