### ISSUE TITLE
Restore documentation page

### ISSUE THREAD

**Issue by Grandmaster** [duckpunch/godash#49]
The documentation page no longer displays all of the functions of godash.

**Comment by duckpunch** [comment]
Which is missing?

**Comment by duckpunch** [comment]
The documentation link is here, by the way: https://duckpunch.github.io/godash/api/

**Comment by duckpunch** [comment]
If you meant the README, I just checked it.  Thanks for catching :)

If you meant something else, let me know!

**Comment by Grandmaster** [comment]
Yeah it was the link in the README. Thanks for your quick reply, and for
taking a look at the issue.
