### ISSUE TITLE
TypeError: godash.Board is not a constructor

### ISSUE THREAD

**Issue by kendfrey** [duckpunch/godash#53]
The following code, when run in node.js, errors with `TypeError: godash.Board is not a constructor`.
```js
var godash = require('godash');
var board = new godash.Board(19);
```

In fact, `godash.Board` is undefined and `godash` seems to be empty.

**Comment by duckpunch** [comment]
Interesting.  Not my normal use case, but I'll take a look.

**Comment by duckpunch** [comment]
Ok, this should be fixed in the latest version.

Thanks for reporting!
