### ISSUE TITLE
What is the license?

### ISSUE THREAD

**Issue by joelanman** [duckpunch/godash#72]
Hi, this looks nice, I'm thinking of using it in a personal project - what is the license?

**Comment by duckpunch** [comment]
Hi @joelanman, thanks!

I just took [the default NPM one - ISC](https://en.wikipedia.org/wiki/ISC_license).  See [here](https://github.com/duckpunch/godash/blob/master/package.json#L22).

I guess I could make it explicit with a `LICENSE` file.

**Comment by joelanman** [comment]
thanks! If my project gets anywhere I'll let you know
